### ISSUE TITLE
Use static page generator

### ISSUE THREAD

**Issue by not7cd** [hs3city/hs3.pl#1]
Obstawiam, że nie będzie to najbardziej ruchliwy "blog".
Mimo wszystko przydało by się jakieś zarządzanie treścią, ułatwi to przyszłe dodawanie zawartości.
https://www.staticgen.com/

**Comment by ksiadz** [comment]
Był wcześniej blog, nikt nie pisał, więc osunęliśmy.

**Comment by not7cd** [comment]
Ok. Backport strony na Jekyll'a nie powinien zaszkodzić

**Comment by not7cd** [comment]
Backport zrobiony :stuck_out_tongue:

**Comment by not7cd** [comment]
Zrobione :stuck_out_tongue_closed_eyes:
