### ISSUE TITLE
Use copyright mixin instead of clean ASCII character. 

### ISSUE THREAD

**Issue by olo2552** [hs3city/hs3.pl#37]
https://github.com/hs3city/hs3city.github.io/blob/ad43120d6dde71371a6c36af10101426db593a19/_includes/footer.html#L17

If we were to change all the copyright signs, than we would have to do it manually in every place. It's typical usage for `mixin`.

**Comment by yasiupl** [comment]
Fixed by changing Copyright to Kopyleft.
