### ISSUE TITLE
fix scrolling on the website 

### ISSUE THREAD

**Issue by tgbdc7** [hs3city/hs3.pl#4]
focus on the https://hs3.pl/finanse

**Comment by Lukortech** [comment]
Could you share more info on what to repair? 
I've checked both mobile and pc view and all seems fine, but my guess would be [this commit](https://github.com/filiphagan/hs3.pl/commit/8bca86a254fb6732392abcef837307c97471c0f5) might have taken care of the problem you had previously.

**Comment by DoomHammer** [comment]
@tgbdc7 ?

**Comment by tgbdc7** [comment]
Yes, scrolling already works
