### ISSUE TITLE
Przygotować "automatyczną" wizualizację budżetu

### ISSUE THREAD

**Issue by DoomHammer** [hs3city/hs3.pl#5]
W tej chwili korzystamy ze statycznie wygenerowanego zrzutu stanu budżetu na połowę zeszłego roku: https://hs3.pl/finanse/

Obecne finanse prezentują się następująco: https://github.com/hs3city/hs3.pl/blob/main/finanse/finanse.csv

Przydałby się mechanizm który automatycznie generuje wykres (może być prosty pokazujący tylko przychody i koszta) i wrzuca na stronę.

Może to być rozwiązanie w JS które działąa po stronie użytkownika albo skrypt w NodeJS, Python, czy czymkolwiek innym kóry generuje odpowiedni obrazek (wtedy możemy to spiąć z GitHub Actions).

**Comment by filiphagan** [comment]
Wrzuciłem pull request z propozycją skryptu

**Comment by Lukortech** [comment]
@DoomHammer daj znać czy do zamknięcia.
