### ISSUE TITLE
Dodać link do Patronite

### ISSUE THREAD

**Issue by Dreat** [hs3city/hs3.pl#8]
https://patronite.pl/hs3/description

**Comment by Lukortech** [comment]
![image](https://user-images.githubusercontent.com/26508593/142779182-f4cfbbb3-f8ee-42b9-a068-09a599a56704.png)

Poszukam gdzieś indziej ;)

**Comment by Lukortech** [comment]
@Dreat issue do zamknięcia, źle podlinkowałem PR do tego :)

**Comment by Lukortech** [comment]
@DoomHammer ewentualnie ;)
