### ISSUE TITLE
Logo w tle - animacja obracania?

### ISSUE THREAD

**Issue by d33tah** [hs3city/hs3.pl#88]
Hej,

Bawiłem się tym chwilę i nie udało mi się osiągnąć efektu. Może dobrym pomysłem byłoby żeby ten SVG w tle się obracał?

**Comment by not7cd** [comment]
W sumie nie wiem jak to ugryźć, ponieważ element jest ładowany jako background. SVG łatwo modyfikować gdy jest zaembedowany w HTML. Można spróbować go jakoś wstawić bezpośrednio i pobawić się `z-level`

**Comment by d33tah** [comment]
@not7cd a co sądzisz o samym pomyśle?

**Comment by d33tah** [comment]
@not7cd a jakby sam SVG się animował?

**Comment by not7cd** [comment]
w tych sztukach nie jestem obeznany

**Comment by d33tah** [comment]
@not7cd zerknij na #90 i powiedz czy Ci się podoba ;)
